# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 3.7.0
maven_group = net.rexbrx.mynt
archives_name = mynt
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.1
parchment_mappings = 2024.11.17

# Dependencies
architectury_api_version = 13.0.8
fabric_loader_version = 0.19.3
fabric_api_version = 0.116.14+1.21.1
neoforge_version = 21.1.215
neoform_version = 20240808.144430
gecko_lib_version=4.8.3


#maven
mavenCentralPublishing=true
signAllPublications=true

mavenCentralUsername=oQaHev
mavenCentralPassword=d0xXGrUQO4M5cgcTFSX1WWyCg5LKt3D77


signing.keyId=561A1E78F78EF9F6
signing.password=mynt4
signing.secretKeyRingFile=/Users/guilherme/.gnupg/trustedb.gpg